name: Build and Deploy to VPS

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build project (SSR)
        run: npm run build

      - name: Deploy dist/ to VPS (r312s)
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22014
          source: "package.json, dist/*"
          target: "/var/www/r312s/"
          strip_components: 1
          rm: false
          overwrite: true
          debug: true

      - name: Install runtime deps + (re)start PM2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22014
          script: |
            cd /var/www/r312s/server
            npm i
            npm install astro
            npm install send server-destroy
            PORT=8082 pm2 restart r312 || PORT=8082 pm2 start entry.mjs --name r312
